# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161115_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='on_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='the related event'),
        ),
    ]
