# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('pub_date', models.DateField(null=True, verbose_name='date published')),
                ('bgg_rating', models.FloatField(default=0.0)),
                ('bgg_bayesrating', models.FloatField(default=0.0)),
                ('bgg_weight', models.FloatField(default=0.0)),
                ('min_players', models.IntegerField(default=1)),
                ('max_players', models.IntegerField()),
                ('best_player_count', models.IntegerField(null=True)),
                ('min_playtime', models.IntegerField()),
                ('max_playtime', models.IntegerField()),
                ('img_link', models.URLField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.ManyToManyField(to='boardgames.BoardGame')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('games', models.ManyToManyField(to='boardgames.BoardGame')),
            ],
        ),
        migrations.AddField(
            model_name='boardgame',
            name='designed_by',
            field=models.ManyToManyField(to='boardgames.Designer'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='tags',
            field=models.ManyToManyField(to='boardgames.Tag'),
        ),
    ]
